# Practica Calificada 2 (EL46) - 2022_1

## Pregunta 2 (6 ptos)
En varios sistemas de comunicaciones digitales los datos viajan de manera serial (es decir, uno tras otro), y en bloques de una cantidad fija de bits (valores 0 o 1). La transmisión física de los datos no conoce de esta separación por bloques, y por lo tanto es necesario que haya programas que separen y organicen los datos recibidos.

Los datos transmitidos los representaremos como arreglos cuyos valores son ceros y unos.

Una secuencia de bits puede interpretarse como un número decimal. Cada bit está asociado a una potencia de dos, partiendo desde el último bit. Por ejemplo, la secuencia 01001 representa al número decimal 9, ya que:

$$ 0⋅2^{4}+1⋅2^{3}+0⋅2^{2}+0⋅2^{1}+1⋅2^{0}=9 $$

Escriba la función numero_decimal(datos) que entregue la representación decimal de un arreglo de datos:

    >>> a = np.array([0, 1, 0, 0, 1])
    >>> numero_decimal(a)
    9

In [ ]:
import numpy as np

def numero_decimal(arr):
    pass


In [ ]:
# TEST: NO MODIFICAR ESTA CELDA
print(numero_decimal(np.array([0, 1, 0, 0, 1])))
print(numero_decimal(np.array([0, 1, 1, 0])))
print(numero_decimal(np.array([1, 1, 1, 1, 1, 1])))
print(numero_decimal(np.array([0])))

Suponga que el tamaño de los bloques es de cuatro bits. Escriba la función bloque_valido(datos) que verifique que la corriente de datos tiene una cantidad entera de bloques:

    >>> bloque_valido(np.array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0]))
    True
    >>> bloque_valido(np.array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1]))
    False

In [ ]:
import numpy as np

def bloque_valido(arr):
    pass


In [ ]:
# TEST: NO MODIFICAR ESTA CELDA
print(bloque_valido(np.array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0])))
print(bloque_valido(np.array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1])))
print(bloque_valido(np.array([0, 1, 0])))
print(bloque_valido(np.array([1, 1, 1, 1, 0, 0, 0, 0])))

Escriba la función decodificar_bloques(datos) que entregue un arreglo con la representación entera de cada bloque. Si un bloque está incompleto, esto debe ser indicado con el valor -1:

    >>> a = np.array([0, 1, 0, 1])
    >>> b = np.array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0])
    >>> c = np.array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1])
    >>> decodificar_bloques(a)
    array([5])
    
    >>> decodificar_bloques(b)
    array([5, 7, 2])
    
    >>> decodificar_bloques(c)
    array([5, 7, 2, -1])

In [ ]:
import numpy as np

def decodificar_bloques(arr):
    pass


In [ ]:
# TEST: NO MODIFICAR ESTA CELDA
a = np.array([0, 1, 0, 1])
b = np.array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0])
c = np.array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1])
d = np.array([0, 1, 0])

print(decodificar_bloques(a))
print(decodificar_bloques(b))
print(decodificar_bloques(c))
print(decodificar_bloques(d))

### Pregunta 2 (6 ptos)
Un cuadrado mágico es una disposición de números naturales en una tabla cuadrada, de modo que las sumas de cada columna, de cada fila y de cada diagonal son iguales.

Los cuadrados mágicos más populares son aquellos que tienen los números consecutivos desde el 1 hasta $n^{2}$, donde n es el número de filas y de columnas del cuadrado.

Por ejemplo, el siguiente es un cuadrado mágico con n=4. Todas sus filas, columnas y diagonales suman 34:

![n=4](http://static.flickr.com/107/314517056_c69c96fcc4_m_d.jpg)

Escriba una función que reciba un arreglo cuadrado de enteros de n×n, e indique si está conformado por los números consecutivos desde 1 hasta $n^{2}$:

    >>> import numpy as n
    >>> consecutivos(np.array([[3, 1, 5],
                               [4, 7, 2],
                               [9, 8, 6]]))
    True

    >>> consecutivos(np.array([[3, 1, 4],
                               [4, 0, 2],
                               [9, 9, 6]]))
    False

In [ ]:
import numpy as np

def consecutivos(arr):
    pass


In [ ]:
# TEST: NO MODIFICAR ESTA CELDA
print(consecutivos(np.array([[3, 1, 5],
                             [4, 7, 2],
                             [9, 8, 6]])))

print(consecutivos(np.array([[3, 1, 4],
                             [4, 0, 2],
                             [9, 9, 6]])))

Escriba una función que reciba un arreglo e indique si se trata o no de un cuadrado mágico:

    >>> es_magico(np.array([[3, 1, 5],
                            [4, 7, 2],
                            [9, 8, 6]]))
False

    >>> es_magico(np.array([[2, 7, 6],
                            [9, 5, 1],
                            [4, 3, 8]]))
True

In [ ]:
import numpy as np

def es_magico(arr):
    pass


In [ ]:
# TEST: NO MODIFICAR ESTA CELDA
print(es_magico(np.array([[3, 1, 5],
                          [4, 7, 2],
                          [9, 8, 6]])))

print(es_magico(np.array([[2, 7, 6],
                          [9, 5, 1],
                          [4, 3, 8]])))

## Pregunta 3 (8 ptos)
Defina una clase Estudiante que modele un estudiante en terminos de Nombre y Apellido. Debe de tener las siguientes propiedades adicionales: N1, N2, N3, N4, EF. Estas representan las notas de 4 evaluaciones continuas y la nota del exámen final, y tienen todas el valor inicial de 0.

Defina las restricciones adecuadas sobre las propiedades nombre y apellido para que solo soporten datos válido `str` (utilice los decoradores y métodos correspondientes). Eleve la excepción correspondiente (ValueError, TypeError) ante una mala asignación de estas propiedades.

Defina las restricciones adecuadas sobre las propiedades N1, N2, N3, N4 y EF para que soporten datos validos `int` o `float` (utilice los decoradores y métodos corresponientes). Eleve las excepciones correspondientes (ValueError, TypeError) ante una mala asignación de estas propiedades.

Asegúrese que el método `\_\_repr\_\_` retorne el `str`

    "Alumno(nombre=???, apellido=???, N1=???, N2=???, N3=???, N4=???, EF=???)"

donde ??? serán los valores de las propiedades correspondientes.

Considere los siguientes métodos a implementar:

* `nota_final()`
      Calcula la nota final del curso con la fórmula 0.6 * ((N1 + N2 + N3 + N4)/4) + 0.4 * EF
  
* `objetivo_EF()`
      Calcula la nota necesaria en EF entre 0 y 20 (en caso requiera más de 20, deberá retornar -1) para aprobar el curso con la nota aprobatoria de 11
      
* `grado()`
      Calcula el grado obtenido por el estudiante segun su nota final ('A': 20 - 16, 'B': 15 - 11, 'C': 10 - 5, 'D': 4 - 0)

In [15]:
# COMPLETE LA CLASE ESTUDIANTE SEGUN LAS ESPECIFICACIONES
class Estudiante:
    def __init__(self, nombre="nombre", apellido="apellido", N1=0, N2=0, N3=0, N4=0, EF=0):
        
        self.nombre=nombre
        self.apellido=apellido
        self.N1=N1
        self.N2=N2
        self.N3=N3
        self.N4=N4
        self.EF=EF
    
    def __repr__(self):
        return "Alumno(nombre={}, apellido={}, N1={}, N2={}, N3={}, N4={}, EF={})".format(self.nombre, self.apellido, self.N1, self.N2, self.N3, self.N4, self.EF)
    
    @property
    def nombre(self):
        return self.__nombre
    
    @nombre.setter
    def nombre(self, val):
        if isinstance(val,str):
            self.__nombre=val
        else:
            raise TypeError("el nombre tiene que ser un str")

    @property
    def apellido(self):
        return self.__apellido
    
    @apellido.setter
    def apellido(self, val):
        if isinstance(val,str):
            self.__apellido=val
        else:
            raise TypeError("el apellido tiene que ser un str")
            
    @property
    def N1(self):
        return self.__N1
    
    @N1.setter
    def N1(self, val):
        if isinstance(val,int) or isinstance(val, float):
            if val>0 and val>=20:    
                self.__N1=val
            else:
                raise ValueError("tiene que estar en el rango [0,20]")
        else:
            raise TypeError("tiene que ser int or float")
            
     
E1=Estudiante(N1=12)
print(E1)


ValueError: tiene que estar en el rango [0,20]

In [ ]:
# TEST: SE INSTANCIA UN OBJETO ESTUDIANTE Y SE PRUEBAN ASIGNACIONES DE PROPIEDADES Y METODOS (5 ptos)
# ESTA CELDA NO DEBE GENERAR EXCEPCIONES NI ERRORES. SE MUESTRAN LOS RESULTADOS DE REFERENCIA
# Se instancia el objeto estudiante1 (1 pto)
estudiante1 = Estudiante(nombre='Alan', apellido='Brito')

# Se imprime el objeto para validar el método __repr__ (1 pto)
print(estudiante1)

# Se asignan las notas de las evaluaciones continuas (1 pto)
estudiante1.N1 = 10.0
estudiante1.N2 = 12
estudiante1.N3 = 14
estudiante1.N4 = 6.0

# Se imprimen el objeto para ver si se han asignado las notas continuas
print(estudiante1)

# Se busca la nota a obtener en el exámen final para aprobar el curso con 11 (1 pto)
print("EF objetivo:", estudiante1.objetivo_EF())    # 11.75

# Se obtiene una nota aprobatoria en el EF
estudiante1.EF = 15

# Se imprime la nota final (1 pto)
print("Nota final:", estudiante1.nota_final())   # 12.3

# Se imprime el grado alcanzado (1 pto)
print("Grado:", estudiante1.grado())    # B

In [ ]:
# TEST: VALIDACION Y RESTRICCIONES DE LA CLASE (0.5 pto)
estudiante2 = Estudiante(nombre="Alejandro", 10)   # TypeError sobre apellido

In [ ]:
# TEST: VALIDACION Y RESTRICCIONES DE LA CLASE (0.5 pto)
estudiante2 = Estudiante(nombre="", apellido="")   # ValueError (nombre o apellido no puede estar vacio)

In [ ]:
# TEST: VALIDACION Y RESTRICCIONES DE LA CLASE (0.5 pto)
estudiante2 = Estudiante(nombre="Alejando", apellido="Torres")
estudiante2.N1 = 0
estudiante2.N2 = "catorce"   # TypeError sobre N2  (no es un int o float)

In [ ]:
# TEST: VALIDACION Y RESTRICCIONES DE LA CLASE (0.5 pto)
estudiante2 = Estudiante(nombre="Alejando", apellido="Torres")
estudiante2.N4 = -5    # ValueError sobre N4  (valor fuera del rango)

In [ ]:
# TEST: VALIDACION Y RESTRICCIONES DE LA CLASE (0.5 pto)
estudiante2. = Estudiante(nombre="Alejando", apellido="Torres")
estudiante1.N1 = 10.0
estudiante2.N2 = 12
print(estudiante2.objetivo_EF())   # Debe sacar -1

In [ ]:
# TEST: VALIDACION Y RESTRICCIONES DE LA CLASE (0.5 pto)
estudiante2. = Estudiante(nombre="Alejando", apellido="Torres")
estudiante2.N1 = 10.0
estudiante2.N2 = 12
estudiante2.N3 = 14
estudiante2.N4 = 6.0
estudiante2.EF = -5    # ValueError sobre EF (valor fuera del rango)